### ISSUE TITLE
Why can't Arbitrary have a simple `map` function?

### ISSUE THREAD

**Issue by peterjoel** [jsverify/jsverify#104]
`smap` requires an inverse mapping function, which isn't always practical. Is this complexity related to shrinking?

I want to be able to write things like:

     var percentage = jsc.number(0,100).map( v => v.toFixed(2) + "%" )

It would be a bit of a pain to have to write an inverse function for that. Should I instead do this:

     var percentage = jsc.bless( {
             generator: jsc.number(0,100).generator.map( v => v.toFixed(2) + "%" )
     })

?

**Comment by phadej** [comment]
Shortly: *yes*. Omitting shrinking feels pragmatic at first, but as soon as your properties start to fail, you'll like to have shrinking. And if your properties never fail, are they worth writing?

In your example, the *inverse* function is quite trivial:
```js
parseFloat("0.99%"); // 0.99
```

**Comment by peterjoel** [comment]
Yeah, my actual example is a bit more complex that that. There is no "true" inverse for it either. Will it be a problem for shrinking if the inverse maps multiple different values to the same?

**Comment by peterjoel** [comment]
Also, if I map on the generator instead, will I lose shrinking anyway?

**Comment by phadej** [comment]
There will be no problem if inverse is not "true", as the documentation of `smap` says:
> `g` should be a [right inverse](http://en.wikipedia.org/wiki/Surjective_function#Surjections_as_right_invertible_functions) of `f`.

I'll add an example illustrating that:
```js
var setNatArb =  jsc.array(jsc.nat).smap(_.uniq, _.identity);
```

Right inverse means that *f(g(y)) = y* for all *y* in *Y*. Here *Y* is a type of **arrays of unique natural numbers**. For them
```js
_.uniq(_.identity(y)) = _.uniq(y) = y
```

Opposite: *g(f(x))* for all *x* in *X*, doesn't need to hold. *X* is **arrays of natural numbers**:
```js
_.identity(_uniq([0, 0])) = [0]] != [0, 0]
```

For shrinking the right inverse is enough. We can always *pull back* `smap`ped value and shrink the preimage, and *map* or *push forward* shrinked preimages again.

---

If someone can explain this in less *math*-way, yet still precisely, i'll appreciate that.

**Comment by joneshf** [comment]
I think the explanation you just gave is good. The example makes it clear what you mean, and how you can have one inverse and not the other.
