### ISSUE TITLE
How to limit the size of data in forall?

### ISSUE THREAD

**Issue by peterjoel** [jsverify/jsverify#106]
I am testing properties of objects that have complexity `O(m * n)`, so it is very slow when large inputs are created. How can I limit the size of the data generated by `forall`?

**Comment by phadej** [comment]
Valid concern! I'll make a special `small` arbitrary for that, which will create `log2` sized objects:

I.e. one could (soon) do:
```js
jsc.property("high complexity algorithm property", "(small array) int", function (arr) {
  return /* property with small array of normal ints ... */;
});
```
or if one wants small array of small ints:
```js
jsc.property("high complexity algorithm property", "small (array int)", function (arr) {
  return /* property with small array of small ints ... */;
});
```
