### ISSUE TITLE
Error when using smap on a fn/fun arbitrary

### ISSUE THREAD

**Issue by peterjoel** [jsverify/jsverify#107]
The same thing happens with either `jsc.fun` and `jsc.fn` (as an aside, I'd like to know the difference).

The following:

      jsc.fn( jsc.integer()).smap( v => {data:v}, t => t.data)

produces an error:

        TypeError: arb.generator.map is not a function
            at Object.arbitraryProtoSMap [as smap]
            at Object.<anonymous>

For sanity, I checked with an integer arbitrary instead, and it works ok:

      jsc.integer().smap( v => {data:v}, t => t.data) // No error

**Comment by phadej** [comment]
I'll fix that tomorrow.

Btw, you'd probably want
```js
jsc.fn( jsc.integer()).smap( v => ({data:v}), t => t.data)
```
parentheses around `{}` are important in ES6 fat arrows!

**Comment by phadej** [comment]
Fixed in current master. While writing the regression test I realised you'd probably want:
```js
jsc.fn( jsc.integer()).smap(
  f => (x) => ({ data: f(x)}),
  f => (x) => f(x).data);
```

**Comment by peterjoel** [comment]
Thanks!

I was writing a test for Applicative laws, and needed unevaluated functions wrapped in the applicative container. I was simplifying for the example code. But you did make me realise that I made a mistake; I'm only generating singletons with this method, while my container can contain multiple values.
