### ISSUE TITLE
call stack size exceeded

### ISSUE THREAD

**Issue by acthp** [jsverify/jsverify#112]
Bumping up the number of test runs results in a blown stack. We need this for hitting more edge cases, e.g. a bug when two numbers happen to be the same. We won't hit that with 100 runs, or 1000 runs.

Looks like the problem is the recursive `loop()` method in jsverify.js. I was confused for a moment by functor.map, which looks like it's storing a thunk, but it's really an immediate invocation. So `loop()` is recursive, and will blow the stack. The js engines really can't handle recursion. If you add a babeljs build and rewrite loop w/o functor.map, babel can handle a TCO, but otherwise I believe a loop is needed to avoid this.

**Comment by phadej** [comment]
For a quick workaround, you can use any promise library to overcome this issue. I have to implement trampoline for synchronous cases though.

**Comment by StoneCypher** [comment]
you can run `node --stack-size=` while you wait for this language to join the 1970s

**Comment by phadej** [comment]
Fixed in `0.6.2`. Sorry it took so long.
