### ISSUE TITLE
jsc.property missing stack trace

### ISSUE THREAD

**Issue by SystemParadox** [jsverify/jsverify#115]
When running jsc.property tests with mocha, if an exception occurs it produces output like this:

```
Error: Failed after 6 tests and 0 shrinks. rngState: 84a5f3e91248d6bc70; Counterexample: {}; Exception: foobar is not defined
```

But no stacktrace is shown.

It would be really helpful if this could be fixed.

Thanks.

**Comment by phadej** [comment]
Fixed in `0.6.1`. Sorry it took so long.
