### ISSUE TITLE
Built-in shrinker for "json" type

### ISSUE THREAD

**Issue by joshuawarner32** [jsverify/jsverify#122]
I'm experimenting with a simple alternative json encoding, using jsverify to check that a simple round-trip works, across a wide range of inputs.  Specifically, I'm using this:

```
jsc.assert(jsc.forall("json", (tree) => 
    JSON.stringify(deminify(minify(tree))) == JSON.stringify(tree)));
```

Here, `minify` and `deminify` are the encoding and decoding routines, respectively.  The details are immaterial, I think.

That works great, and seems to be finding bugs - but it's not shrinking.  I'm consistently seeing `Error: Failed after <n> tests and 0 shrinks.`.

Questions:
* Is this user error?  Do I have to enable shrinking somehow?  Is there something I could be doing in `deminify` and `minify` that's causing shrinking to fail?
* If it's not user error, is it something should be (in your view) included in jsverify, or should I look elsewhere, or write a purpose-built one?
* Writing a shrinker in the general sense is obviously not difficult; I've done it before in other contexts.  However, the documentation doesn't make it clear (to me) how it needs to be integrated with jsverify.  Any pointers?

**Comment by phadej** [comment]
There is a long standing issue to implement shrinking of `json` values. Sorry that not being reflected in the documentation.

If you can implement the shrink it will be wonderful, you can experiment by:

```js
var jsonShrink = function (json) { /* ... * / };
var betterJsonArb = jsc.bless({
  generator: jsc.json.generator,
  show: jsc.json.show,
  shrink: betterJsonArb
});
```

Also you can use *user environment* to override `json` in DSL approach:

```js
var userEnv = { json: betterJsonArb };

jsc.property("deminify . minify = id", "json", userEnv, function (json) {
  /* ... */
});
```

**Comment by joshuawarner32** [comment]
Cool.  I wasn't able to figure out how to use `jsc.property` (the VM complained of an undefined global `it`, which is mentioned in the documentation - but I can't make heads or tails of the how or why there).  However, `jsc.assert(jsc.foreach(...))` continued to work fine for me.

I have a passable json simplifier implemented here (forgive the typescript type annotations): https://gist.github.com/joshuawarner32/14988fb48cf1a452fb3e.

There are two problems:
* I'm unsure of how to delegate to jsverify's shrinkers for numbers, strings, booleans, etc.
* Right now, I'm returning an array of possible shrinks, which can grow quite large and be highly redundant between successive shrinking steps.  It looks like there's some support for `lazyseq`s, which I think is what I want - except, it seems to me using that will turn the code into a awful mess of closures.  Suggestions welcome.

**Comment by phadej** [comment]
I can continue from here. This could be a good topic for a tutorial too. Ping me at the end of the next week if I forget about this. Hopefully this isn't blocking you too much.

And you can shrink number with `jsc.number.shrink`. And there is `jsc.shrink.array(elementsShrink)` IIRC. some (most?) shrinks return lazyseq though..

**Comment by phadej** [comment]
Sorry for the delay, I try to assemble [0.7.0](https://github.com/jsverify/jsverify/milestones/0.7.0) as soon as possible.
