### ISSUE TITLE
Generalize result

### ISSUE THREAD

**Issue by joneshf** [jsverify/jsverify#127]
What do you think about moving from specifically booleans to a more generalized approach like [Testable](http://hackage.haskell.org/package/QuickCheck-2.8.1/docs/Test-QuickCheck-Property.html#t:Testable)?

I'd like to be able to attach reasons to errors, among other things, and booleans don't carry enough information with them for this.

**Comment by phadej** [comment]
Yes!

Currently only `true` in considered as *successful* value, so:
```js
> jsc.check(jsc.forall("nat", function (n) { return "cause: " + n; }))
Failed after 1 tests and 6 shrinks. rngState: 00da3714f9c2058eb6; Counterexample: 0;  [ 0 ]
```

You don't see the non-`true` value though, but it should be easy to add, as we show exceptions (which are current workaround):

```js
> jsc.check(jsc.forall("nat", function (n) { throw new Error("cause: " + n); }))
Failed after 1 tests and 4 shrinks. rngState: 0adc76385e20ab149f; Counterexample: 0; Exception: cause: 0
```

**Comment by joneshf** [comment]
Oh, I see. So the quick way to go about this is to just wrap up that difference in a function.

```js
function assert(b, msg) {
  if (b) {
    return b;
  } else {
    throw new Error(msg);
  }
}
```
But that seems really dirty.

**Comment by phadej** [comment]
```js
> jsc.assert(jsc.forall("nat", function () { return "foobar"; }));
Error: Failed after 1 tests and 6 shrinks. rngState: 0073892e5dfbc4a016; Counterexample: 0; Error: foobar
```
