### ISSUE TITLE
Shrinker for falsy

### ISSUE THREAD

**Issue by ashnur** [jsverify/jsverify#129]
I have trouble understanding how shrinkers work. I need to test a very complicated generator which at some point can return any kind of falsy values, including undefined. I can not imagine what a shrinker for that generator would look like. I tried to search for explanations or documentations both in this repository and on the web, but couldn't find anything which would've helped me out. I am sure I am missing something, but what is that?

**Comment by joneshf** [comment]
In most cases, you'll get more milage by reusing the primitives that exist. `either`, `tuple` and `record` I've found are very useful to build up complex arbitraries. Using those along with `smap`ing to generate the actual value you want usually makes it easier to deal with. And they handle shrinking on their own.

Can you describe your arbitrary?
What types of values do you want to produce?

**Comment by ashnur** [comment]
I writing tests for a an arbitrary precision rational number library. This library exposes a number of functions, but the hardest to test is the factory itself. It can take 1 or 2 arguments and I would want to test with all combinations javascript "types" of them. Afaiu I need a generator of values of kinds: all falsy and `true`, strings, numeric strings, numbers (including `NaN` and the `Infinities`)
Some combinations are invalid and should throw an Error others maybe behave differently from each other.
Now I  figured I should do all the testing in one big blob, but try to separate everything however I still need stuff like (undefined, 1) because it's not yet defined if that's an error or just zero or maybe else.
The majority of the tests will have no issues in shrinking, because it's all arithmethic, but these strange combinations I am not sure how I should approach.

**Comment by phadej** [comment]
If I understand your problem right, you could write tests like:

```js
jsc.property("throws when passed single falsy value", "falsy", function (f) {
  return jsc.throws(function () {
    createNewRational(f);
  });
});

jsc.property("works with numeric string", "number", function (n) {
  var r = createNewRational(new String(n));
  return r.toJavascriptNumber === n;
});

// etc.
```

**Comment by ashnur** [comment]
I am not sure how this would help me create a shrinker? Ultimately I need one single generator of rational numbers given any kind of input, otherwise i would have to reimplement the same tests multiple times. Unless I misunderstand something, of course.

**Comment by ashnur** [comment]
Just to extend on the last comment. I definitely do not need all falsy to fail, it's quite rare for any function to fail when it gets falsy values, usually we have defaults or it means that the first argument has to treated in a different way.

**Comment by phadej** [comment]
I'm personally very confused, what kind of properties (i.e. tests) do you want to write (please write code, prose is very ambiguous) ? If your property takes *"any kind of input"*, what you can assert based on that?

You can have `jsc.sum([jsc.falsy, jsc.number, jsc.string])` arbitrary, but I suspect you try to use jsverify in a way it's not designed for.

**Comment by ashnur** [comment]
@phadej You may be very right about your guesses. So this is what I am trying to do right now:

https://gist.github.com/ashnur/7ee37a0a01110b0a58c7

Seems to be working, but the shrinker part is still a mist for me. Nevertheless using this I think I can start implementing there rest of the tests.

**Comment by phadej** [comment]
As @joneshf mentioned, you should use combinators on arbitraries. There is an arbitrary `jsc.falsy`, witch has `generator` and `shrink` provided.

I'll add a notice that to not recommend using `jsc.generator` functions directly, in most cases they are too low-level.

**Comment by phadej** [comment]
And another comment, by using external random generator (`mt19937`) you omit test determinism. If you think that jsverify built-in generator isn't good enough, open issue about that, and we'll see what we can do.

**Comment by ashnur** [comment]
Well, one thing is sure, the knowledge gap between us is huge. You all seem to be so confident about what I should do that you just say "use combinators on arbitraries". No response on any of my questions regarding if it's even possible what I want to do. (I assume yes, but have no idea how), and you definitely
 seem very irritated about me not already knowing what you know. 
I tried what you are saying when I first found jsverify, and couldn't do shit with arbitraries. I just can not imagine how that would work in my case.

**Comment by phadej** [comment]
```js
var jsc = require("jsverify");
var shrinkBool = jsc.bool.shrink;
var shrinkFalsy = jsc.falsy.shrink;
```

Instead of writing

```js
// generates either booleans or falsy values
var myArb = jsc.bless({
  generator: function (size) {
    var n = jsc.random(0, 1);
    switch (n) {
      case 0: return jsc.bool.generator(size);
      case 1: return jsc.falsy.generator(size);
    }
  },

  shrink: function (value) {
    // shrink bool to false
    if (value === true) {
      return [false];
    } else {
      // falsy
      return jsc.falsy.shrink(value);
    }
  }
});
```

write:

```js
function toMy(s) {
  // forget how we generated s
  return s.fold(function (idx, len, value) {
  	return value;
  });
}

// "reverse" of toMy
// won't be mandatory in 0.8.0 (current plan): https://github.com/jsverify/jsverify/issues/111
function fromMy(v) {
  // put `true` value in first bucket
  // `false` could be generated by either one, I decided to put it in the second.
  if (v === true) {
  	return s.addend(0, 2, v);
  } else {
    return s.addend(1, 2, v);
  }
}

var myArb = jsc.compile("bool | falsy").smap(toMy, fromMy);
// or
var myArb = jsc.sum(jsc.bool, jsc.falsy).smap(toMy, fromMy);
```

In this example, especially as "a reverse function" is still required, the snippets are about as lengthy. Yet the latter example is what I'd recommend to use, there aren't `generator` or `shrink` written by hand, neither forgotten `bless` etc.

Sorry for sounding irrogant, but text based & offline communication is hard. Yet I think you hit [XY problem](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem): If you couldn't do shit with arbitraries, ask about that. And I tried to reply, that whatever you are doing, you should try arbitraries first. Look at the example above, if you don't understand something there ask about that (`jsc.sum` is n-ary abstraction of `jsc.either`).

For another, a bit more complicated, yet real world example, see [json arbitrary](https://github.com/jsverify/jsverify/blob/master/lib/json.js). There I have to create `generator` by hand, because structure is recursive. Shrinking of recursive arbitraries is WIP as well.
