### ISSUE TITLE
Questions about making more complex arbitrary A

### ISSUE THREAD

**Issue by hath995** [jsverify/jsverify#137]
I have a number of functions that I would like to test which take some data that is based on other data. For example let's say that I wanted to test a function equivalent to String.split() so lets says
split : string -> string -> [string]
split splitToken strToSplit

I could construct a test by doing 

    jsc.assert(jsc.forall(jsc.pair(jsc.asciistring, jsc.asciistring), function(stringpair ) {
      //various assertions about split(stringpair[0], stringpair[1])
    })))
However this isn't a very good test because most often the generated pairs don't have anything in common. In particular we want splitToken to be a substring of strToSplit

A similar situation I am trying to test is generating a random graph of the form 

    {
      nodes: [string],
      edges: [pair(string, string)] //Where the string values are a in the set of nodes
    }

I wrote the following which gives roughly what I want. However it returns an Arb (Arb B) so when I use sample it returns a Arb B rather than a B

    function genEdges(x) {
        return jsc.record({
            nodes: jsc.constant(x.nodes),
            edges: jsc.array(jsc.tuple(
                [jsc.elements(x.nodes), jsc.elements(x.nodes)]
            ))
        });
    }
    var graphbuilder = jsc.record({nodes: jsc.array(jsc.asciistring)}).smap(genEdges);
    jsc.sampler(graphbuilder)();

What is the correct way to construct dependent test cases like this? 
Thanks

**Comment by phadej** [comment]
The first example is simple. If you need some structural property, construct your value so it has it:
```js
// btw, j`sc.forall` can generate multiple arguments:
jsc.assert(jsc.forall(jsc.asciistring, [jsc.asciistring], function(splitToken, arrToSplit) {
  var strToSplit = arrToSplit.join(splitToken); // now the split token is in the string by construction!
  //various assertions about split(splitToken, arrToSplit);
})));
```

Similarly graph could be constructed by:
```js
function toGraph(nodes, edgesIdx) {
  // (nat, nat) -> (nodeid, nodeid)
  var edges = _.chain(edgesIdx)
    .map(function (e) {
      if (e[0] < nodes.length && e[1] < nodes.length) {
        return [nodes[e[0]], nodes[e[1]]];
      }
    })
    .collect()
    .value();

  return {
    nodes: nodes,
    edges: edges,
  };
}

// the idea is to generate edges not directly, but thru indexes:
var graphArb = jsc.pair(jsc.array(jsc.asciistring), jsc.array(jsc.pair(jsc.nat, jsc.nat))).smap(toGraph, fromGraph);
```

Note: `smap` needs an *inverse* too.

There isn't `flatmap`, maybe there will. There definitely will be `map`.

**Comment by hath995** [comment]
Thanks,
So would the inverse function for the graph look something like

    function fromGraph(graph) {
      var edge_indices = graph.edges.map(function(edge) {
         return [nodes.indexOf(edge[0]), nodes.indexOf(edge[1])]
      });
      return [graph.nodes, edge_indices];
    }

**Comment by phadej** [comment]
Yes, that function looks about right. I *emphasise*, it doesn't need to be proper inverse, just that
```js
toGraph(fromGraph(graph) ≡ graph
```
holds. In this case you don't need to care about the index pairs we drop with `.compact()`.

**Comment by hath995** [comment]
Awesome,
Last couple question, what is the intended use case for the generator and shrink family of functions? It seems like the arbitraries could generate random data for any other conceivable property that one would want to test. What do they give us that Arbitrary doesn't?

**Comment by phadej** [comment]
They lay on the lower level. Sometimes you need more control on how shrinking strategies, especially with recursive data.

**Comment by hath995** [comment]
Interesting, I'll have to think more about that. Thanks again for all your help. It's a very exciting library!
