### ISSUE TITLE
Unexpected behaviour with mocha's beforeEach

### ISSUE THREAD

**Issue by bradleyayers** [jsverify/jsverify#138]
When using the `property` API to create mocha tests, I was surprised that mocha's `beforeEach` was not being called for each check of the property. This makes sense given the implementation, as `beforeEach` will run "before each `it()`", and there's only *one* `it()` per property.

I'm not sure what the right solution is here, perhaps it would make more sense for `property` to expand to multiple `it()` statements, but it's not obvious how this should work, given I wouldn't expect it be supported for dynamic creation of `it()` *during* an `it()`.

Thoughts?

**Comment by phadej** [comment]
What is your use case?
- if you need to run some setup code on each check, put that code into the property computation
- if you need to run some setup code once per property (or some properties): `beforeEach` in a `decribe` block

Or do I miss-understand you?

**Comment by bradleyayers** [comment]
You understand me correctly, and your suggestions are completely valid. I just wanted to let you know of my problem, to serve as a question that future readers may stumble upon.

My problem was that I assumed that `property()` would have the same semantics as `it()`, which I  now realise is obviously not the case. Anyway great library, I look forward to using it more in the future.

**Comment by phadej** [comment]
@bradleyayers I'll reopen this, have to add documentation notice about this. As this is not totally obvious, better to write it down.
