### ISSUE TITLE
Reduce syntax for common use case

### ISSUE THREAD

**Issue by techtangents** [jsverify/jsverify#152]
I anticipate most of my jsverify tests will look like this:

    jsc.assert(jsc.forall(function("type", a) {
      return jsc.util.isEqual(a, z);
    }));

I'd like a more minimal syntax, like this:

    jsc.run(function("type", a) {
      return jsc.eq(a, z);
    });

I'm just trying to minimise the boilerplate, as I'm expecting to write many thousands of these.

**Comment by techtangents** [comment]
BTW if you agree, I'm happy to submit a pull request.

**Comment by phadej** [comment]
well, I use  with mocha (you can see in jsverify tests):

```js
jsc.property("nat", "nat", function (a, b) {
  return a < b;
});
```

But it indeed could make sense to make general
```js
jsc.checkForall("nat", "nat", function (a, b) { return a < b; });
jsc.assertForall("nat", "nat", function (a, b) { return a < b; });
```
which aren't tied to `it`.

PR would be nice.

**Comment by techtangents** [comment]
In my code example, I also had a shortcut for jsc.util.isEqual as jsc.eq. Are you ok with this? Again, just trying to minimise code.
