### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by techtangents** [jsverify/jsverify#153]
I forked, cloned, "npm update", then "make test" and get the below error. I'm using node 4.2.2.

    ☀️ ~/techtangents/jsverify (master)
    ⚡ make test
    node_modules/.bin/jshint lib test fail examples helpers karma.conf.js karma.jasmine.conf.js
    node_modules/.bin/eslint lib test fail examples helpers karma.conf.js karma.jasmine.conf.js

    /Users/dylan/techtangents/jsverify/lib/jsverify.js
      212:57  error  There should be no space before ','  comma-spacing
      212:57  error  A space is required after ','        comma-spacing

    ✖ 2 problems (2 errors, 0 warnings)

    make: *** [eslint] Error 1

**Comment by phadej** [comment]
master is green
