### ISSUE TITLE
Passing `NaN` to a generated function always returns `undefined`

### ISSUE THREAD

**Issue by lvanengelen** [jsverify/jsverify#156]
To reproduce in `node`:

```js
jsc = require("jsverify")
jsc.sampler(jsc.fn(jsc.number))()(NaN)
```

This is caused by `finitemap#get` not matching any value, because `NaN !== NaN`

**Comment by phadej** [comment]
Hmm... I'll check this ASAP

**Comment by lazywithclass** [comment]
Hello, I am looking into this issue, could you please give some more background? 
What should be the expected behaviour?

**Comment by lvanengelen** [comment]
A generated function should return a value of the type as specified using
`jsc.fn`, e.g a number in case of `jsc.number`. However, when passing `NaN`
to such a generated function, it always returns `undefined`. This is
because of the implementation of `FMap`: in `fn.js` the generated function
is created. It uses an `FMap` to keep track of which output was generated
for which input so it can maintain this relationship. However, `NaN` is
weird in that it is defined as not being equal to itself which causes the
lookup in the `FMap` to always fail causing the generated function to
always return `undefined `.

So the methods of `FMap` should be fixed to handle `NaN` properly. Checking
against `NaN` can be done using the  `isNaN` function.
Op 19 apr. 2016 4:25 PM schreef "Alberto Zaccagni" <notifications@github.com

**Comment by lazywithclass** [comment]
Great, thanks for that.
