### ISSUE TITLE
Consider adding `null` and `undefined` values to the `json` datatype.

### ISSUE THREAD

**Issue by boris-marinov** [jsverify/jsverify#170]
Hi, 

I think that when I specify that I want a value of type `json` for a test I should get (among the other values) `null` and `undefined`.

The main reason for this is that these are the only two values for which an error is thrown on property access: 

```
undefined.a
VM234:1 Uncaught TypeError: Cannot read property 'a' of undefined(…)(anonymous function) @ VM234:1
null.a
VM239:1 Uncaught TypeError: Cannot read property 'a' of null(…)
```

So if I have something like

```
if(typeof obj.description === 'string') {
   return obj.description
} else {
   return defaultDescription
}
```

it will break for `obj = null`.

But testing this with

```
property('json', (obj) => {
```

wont catch that error.

**Comment by phadej** [comment]
doesn't `json` include `null`? weird. I'll accept a patch.

**Comment by phadej** [comment]
(won't include `undefined` as it's not valid `json` as it cannot survive `JSON.stringify` `JSON.parse` roundtrip).
