### ISSUE TITLE
List of counterExamples

### ISSUE THREAD

**Issue by Koleok** [jsverify/jsverify#171]
Is there any way to specify a list of counterExamples? For example:

```javascript
const dateRangeCheck = d => d > lowDate && d < highDate;

it('myTest', () => {
  assert(forall('datetime', dateRangeCheck ), { counterExample: [
    new Date('lowOutsideOfRange'),
    new Date('highOutsideOfRange'),
  ]});
});
```

This range case is just the first thing that came to my mind, but i could imagine other cases where you might want to specify a list of `n` cases that _should_ fail

**Comment by phadej** [comment]
How they sre different from normal unit tests then? Can't you `.forEach` the array of counter-examples to see they are such?

**Comment by Koleok** [comment]
My purpose here is just to find a way to test sad paths as well with `jsv`, i guess it would suit my needs to just run two additional asserts where i use the `suchthat` function to produce dates that are above and below range, then assert that the property does *not* hold. Would this be something close to a normal use case? 

I just discovered the awesomeness that is this repo (thanks by way) in the last few days so i am still feeling my way around the cave trying to port some example based tests.

**Comment by Koleok** [comment]
Ok looks like i posted this a bit prematurely, i was thinking that `counterExample` was one of the keys passed on the `options` object 😊 Looks like it is only something provided in a failing test's output.
