### ISSUE TITLE
Define an arbitrary and use it in the DSL?

### ISSUE THREAD

**Issue by boris-marinov** [jsverify/jsverify#175]
Hello,
Can you give me an example on how to define an arbitrary and use it in the DSL?

I have: 
```
jsc.monad = (value) => (bless({
  generator: (num) => Maybe.of(value.generator(num)),
  shrink: () => [],
  show: (maybe) => maybe.toString()
}))
```
It allows me to do:
```
property('ap', jsc.monad(jsc.json), function(m){
```
but not: 
```
property('ap', 'monad json', function(m){
```
How can I make the second example work - tried using`compile`, but I guess I don't understand how it works.

**Comment by joneshf** [comment]
You have to pass in an environment as the penultimate argument:

https://github.com/joneshf/ziparray/blob/391c3bad498b07897cb44d511c53adc782a5fcb4/test.js#L9-L11

https://github.com/joneshf/ziparray/blob/391c3bad498b07897cb44d511c53adc782a5fcb4/test.js#L15

**Comment by boris-marinov** [comment]
Thanks.
