### ISSUE TITLE
Implication with jsverify

### ISSUE THREAD

**Issue by lunaryorn** [jsverify/jsverify#191]
Quickcheck let's you write implications, i.e. `length s >= 0 ==> startsWith s (charAt s 0)`, where the property evaluation is discarded if the implication does not hold.

Can I do the same with jsverify?  I'd essentially need `!contains(values, x) => throws(() => X.fromString(x)))`

**Comment by phadej** [comment]
There is `suchthat` combinator, which would make generator re-try. If you really don't want to retry generation, then `a ==> b` is equivalent to `!a && b`, so you can say:

```js
!contains(values, x) && throws(() => X.fromString(x))
```

I'd accept `jsc.implies = function (a, b) { return !a && b }` PR, which would also work on property objects.

**Comment by joneshf** [comment]
You mean `!a || b`, yeah?

https://en.wikipedia.org/wiki/Material_conditional#Truth_table

**Comment by phadej** [comment]
yeah, sorry.
