### ISSUE TITLE
Mutually recursive arbitraries?

### ISSUE THREAD

**Issue by thejohnfreeman** [jsverify/jsverify#192]
I want to do something like this:

```js
// An arbitrary "case" of the form {seed: any, value: any}
arbCase = jsc.oneof(arb1, arb2, arb3)
// arb1 is the "base case" that does not recurse
arb1 = jsc.bool.smap(
  (bool) => ({seed: bool, value: bool}),
  (kase) => kase.seed)
// arb2, arb3, and so on might want to recurse over each other.
arb2 = arbCase.smap(
  (kase) => ({seed: kase, value: kase.value}),
  (kase) => kase.seed)
arb3 = jsc.tuple(jsc.bool, arbCase).smap(
  ([bool, kase]) => ({seed: [bool, kase], value: kase.value}),
  (kase) => kase.seed)
```

Is this possible? The use case is where the "arbitrary case" is a complete *test case*: the seed maps back to the parameters for its construction, and the value is actually three values (a function, an input, and an expected output):

https://github.com/thejohnfreeman/transformers/blob/master/index.test.js
https://github.com/thejohnfreeman/transformers/blob/master/test/arbitrary.js

**Comment by phadej** [comment]
there isn't ready made combinator. The
```js
{ arb1, arb2 } = menrva.letrec(function (tie) {
  return {
    arb1: jsc.tuple(jsc.int, jsc.oneof(jsc.const(null), tie("arb2")),
    arb2: jsc.tuple(jsc.bool, jsc.oneof(jsc.const(null), tie("arb1")),
  }
});
```
should be implementable (i.e. you have to put the whole recursive group into single `letrec`). I'm not sure whether dsl/typify "compiler" has already something like that (grep for `compileRecursive`).
