### ISSUE TITLE
Shrinking with flatMap

### ISSUE THREAD

**Issue by jvanbruegge** [jsverify/jsverify#211]
To what should I shrink with flatMap? Say I have this generator:
```js
jsc.nat.generator
    .flatMap(n => {
        const t = Array(n).fill(jsc.nat.generator);
        return jsc.generator.pair(jsc.generator.constant(n), jsc.generator.tuple(t));
    })
``` 
How does my shrink work? Is it only a `nat` shrink or something else?

**Comment by phadej** [comment]
You have to write that yourself unfortunately.

One simple solution is to shrink the contains of the "tuple", but keep `n` fixed.

Side-note: 
```javascript
jsc.array.generator.map(arr =>
  [arr.length, arr]
);
```
I.e. I **very** rarely need to rely on `flatMap`: `map` and `combine` are often enough (only exception: generation well-typed lambda calculus terms, but that's quite advanced need, IMHO).

**Comment by jvanbruegge** [comment]
Ok, thanks
