### ISSUE TITLE
oneOf help

### ISSUE THREAD

**Issue by edoloughlin** [jsverify/jsverify#217]
As someone who doesn't have a background in Haskell, I'm really struggling to do anything beyond basic stuff with jsverify. I'd really appreciate a pointer on how I generate oneOf(null, undefined, 0):

`jsc.oneOf([jsc.constant(undefined), jsc.constant(null), jsc.constant(0)])`

doesn't work:

> undefined is not a constructor

What am I missing?

**Comment by edoloughlin** [comment]
Ok, so `falsy `sort of fits my requirement. Is there any documentation on how I might use `oneOf `as above  - the docs are pretty opaque.

**Comment by akiellor** [comment]
@edoloughlin 

I think you may have a typo in your code. Try `oneof` instead of `oneOf` like so:

```javascript
jsc.oneof([jsc.constant(undefined), jsc.constant(null), jsc.constant(0)])
```

**Comment by danr** [comment]
This can probably be closed.

**Comment by phadej** [comment]
I'll leave it to the reporter to close, if their question is answered.
