### ISSUE TITLE
Arbitrary array of arbitrary arbitraries

### ISSUE THREAD

**Issue by lastmjs** [jsverify/jsverify#228]
I want to create an array of arbitrary size, with values that are arbitrary arbitraries. So it would become an array of random size with random values, those values resolving from JSVerify arbitraries.

I want to do something like:
```
jsc.array(jsc.elements([arb1, arb2, arb3]))
```

Any help would be appreciated.

**Comment by phadej** [comment]
`oneof(gs : array (arbitrary a)...) : arbitrary a`

**Comment by lastmjs** [comment]
I think I've got it:

```
jsc.array(jsc.oneof([arbContent, arbVariable]))
```

I don't know why `jsc.elements` does not work in place of `jsc.oneof`.

**Comment by phadej** [comment]
`jsc.elements` takes an array of concrete values

```js
jsc.elements([1, 2, "foo"]) // will generate 1, 2 or "foo"
```
