### ISSUE TITLE
Arbitrary that combines fixed string with arbitrary string

### ISSUE THREAD

**Issue by lastmjs** [jsverify/jsverify#229]
I want to create an arbitrary that returns `var[some arbitrary string]`. There will always be one fixed portion of the string, `var` being that fixed portion.

**Comment by lastmjs** [comment]
I think I've got something:

```
jsc.pair(jsc.constant('var'), jsc.nestring).smap((x) => {
        return x.join('');
    }, (x) => {
        return x.join('')
    })
```

Is there a better way? Am I using `smap` correctly?

**Comment by phadej** [comment]
the simplest way (which still should shrink stuff) would be:

```haskell
jsc.combine(jsc.constant('var'), jsc.nestring, function(x, y) {
  return x + y;
});
```

**Comment by lastmjs** [comment]
I'm getting `jsc.combine is not a function`

**Comment by phadej** [comment]
Ah, I already forgot the API, should not comment without checking.

Then your `pair` variant is almost right, but two functions passed to `smap` should be inverses of each other.
