### ISSUE TITLE
Missing type definitions for jsc.record

### ISSUE THREAD

**Issue by jchapuis** [jsverify/jsverify#232]
It seems jsc.record is missing from the Typescript definitions. 

In addition, it would be a really great addition to be able to get automatic generators for a Typescript class, making tests more resilient to changes in data. See https://github.com/rasmus-storjohann/TsAutofixture for an example of what I mean. Thanks!

**Comment by AlexGilleran** [comment]
Looks like this was already fixed in `master` months and months ago, could we get another release so we can use it? :)

**Comment by AlexGilleran** [comment]
For now you can work around it by copying the tsc file locally and using jsverify like:

```
///<reference path="./jsverify.d.ts" />
import jsc = require("jsverify");
```

**Comment by danr** [comment]
Yep, this can be closed when there is a new npm release.

**Comment by danr** [comment]
This can be closed now.
