### ISSUE TITLE
Resolve an arbitrary outside of `jsc.forall`

### ISSUE THREAD

**Issue by lastmjs** [jsverify/jsverify#238]
I would like to be able to resolve/evaluate arbitraries and get their primitive values outside of passing them into `jsc.forall` so that I can use the arbitraries arbitrarily in my code, anywhere I would like. Is this available in the API?

**Comment by lastmjs** [comment]
Is `sampler` the best way to do this?

**Comment by danr** [comment]
If you have a generator you can simply just call it with a size parameter. If you have an arbitrary, you can access the generator with `.generator`. So here's an example: `jsc.string.generator(10)`.

**Comment by phadej** [comment]
Use sampler, don't call generator directly. The latter is internal-ish API
