### ISSUE TITLE
Exclude certain values from a generator

### ISSUE THREAD

**Issue by nicenemo** [jsverify/jsverify#243]
As a user I want to exclude certain values from a generator.
`E.g. jsc.nat.exclude(42)` will return natural numbers except 42.

If this is already easy possible please tell me (and add it to the documentation).

**Comment by phadej** [comment]
the equality comparison is tricky in JS, use `suchthat`:

```javascript
jsc.nat.suchthat((x) => x !== 42);
```

**Comment by nicenemo** [comment]
Thank you !!
ScalaCheck/FsCheck support it to. Now it is only missing from the documentation.

**Comment by nicenemo** [comment]
@phadej  Where is the `suchthat(...)`  function. It is not in JSVerify or jsverify-contrib?

**Comment by phadej** [comment]
https://github.com/jsverify/jsverify#restricting-arbitraries

**Comment by nicenemo** [comment]
Thank you. But does not work for me.  What am I doing wrong? See what I tried from node REPL

![image](https://user-images.githubusercontent.com/2677108/30263244-6edb0ef8-96d4-11e7-81e4-83dbc3870c60.png)

Dev dependencies in package json:
```
  "devDependencies": {
    "chai": "^4.1.2",
    "eslint": "^4.6.1",
    "form-data": "^2.3.1",
    "fs": "0.0.1-security",
    "jsverify": "^0.8.2",
    "mocha": "^3.5.0",
    "path": "^0.12.7",
    "randexp": "^0.4.6",
    "request": "^2.81.0",
    "request-promise": "^4.2.1",
    "sinon": "^3.2.1",
    "snyk": "^1.40.2"
  }
}
```

**Comment by phadej** [comment]
I remembered the API wrong (the docs are correct!)

```js
jsc.suchthat(jsc.nat, (x) => ...):
```

**Comment by nicenemo** [comment]
Works! thank you.  Confirmation see screenshot

![image](https://user-images.githubusercontent.com/2677108/30263648-198cf3ba-96d6-11e7-9fda-2b739ea07c12.png)
