### ISSUE TITLE
Compose an arbitrary out of guaranteed and random values

### ISSUE THREAD

**Issue by masaeedu** [jsverify/jsverify#254]
I have a property that must be satisfied for all integers in a range, but in particular *must* be tested for the boundaries and 0.  Is there a way to construct an arbitrary that will guarantee the property is tested for integers `a`, `b` and `0`, as well as for some amount of randomly sampled integers between `a` and `b`?

**Comment by CaptJakk** [comment]
I usually do this by composing the arbitraries with `jsc.oneof`

In your case I would just do the following
```js
const arbitrary = jsc.oneof([jsc.constant(0), jsc.constant(a), jsc.constant(b), jsc.integer(min, max)])
jsc.property('test name', arbitrary, () => ...)
```

**Comment by masaeedu** [comment]
@CaptJakk Wouldn't that test just one of the provided generators? As I mentioned above, I need to guarantee that both boundaries and 0 are tested every time I run the tests, in addition to whatever jsverify tests randomly.

**Comment by CaptJakk** [comment]
It would mean that roughly 25% of your tests would be on boundary 1, 25% on boundary 2, 25% 0, and 25% random throughout the range. If you need a guarantee just write a regular test or use jsc.constant(x). The whole point of property based testing is to randomize the inputs. You can definitely combine traditional unit testing and property testing in the same test file.

**Comment by masaeedu** [comment]
That's not really what I want, because it means 75% of the tests are just testing three points repeatedly.

Right now all my tests look like this:

```js
  t.is(encode(min).length, 4);
  t.is(encode(max).length, 4);
  t.is(encode(0).length, 4);

  const prop = jsc.forall(domain, n => encode(n).length === 4);
  t.notThrows(() => jsc.assert(prop));
```

Which is annoying, because for every invariant I am asserting about my function I need to remember to add 4 separate checks.

The theory between property based testing is that by randomly testing over a domain you can obtain some probabilistic certainty that the property you're testing holds over the entire domain. When creating a composite domain, I should be able to explicitly choose my probability threshold (or maximum number of sampled points) for each constituent. 

If that were possible I could require a certainty of 1 (or a trial threshold of infinity) for the minimum, maximum and 0 points, and simply go with the default probability/max sampled points threshold for the remainder of the domain.

**Comment by CaptJakk** [comment]
Right but I’m not sure that any version of that in jsverify can be
expressed more concisely than what you showed above. You’ll never be able
to avoid remembering to do those particular checks as you’d have to encode
their probability thresholds as 1 somehow. From there we’re talking about
how can we concisely express the points on the domain that need to be
favored by some amount. If you have a proposal for what such a solution
would look like at the call site we can try and put something together but
I guess I currently don’t understand what you would want instead.

**Comment by StoneCypher** [comment]
pardon the silly question, but why not just

```javascript
const lengthIsFour = (domain, edges) => {
    edges.map(e => t.is(encode(e).length, 4);
    t.notThrows(() => jsc.assert(
        jsc.forall(domain, n => encode(n).length === 4);
    ));
};
```

Then you could just

```javascript
    lengthIsFour(yourDomain, [0, min, max]);
```
