### ISSUE TITLE
Add explicit .js extension to arbitraryBless require

### ISSUE THREAD

**Issue by lastmjs** [jsverify/jsverify#261]
In `primitive.js`, line 4, the require statement for `arbitraryBless` does not have an explicit .js file extension. This is causing problems in my build system. Nowhere else is the extension removed when requiring `arbitraryBless`, only there. I'd be happy to do a PR if it would be accepted

**Comment by phadej** [comment]
please do

**Comment by lastmjs** [comment]
Here you go: https://github.com/jsverify/jsverify/pull/262
