### ISSUE TITLE
Missing type definitions for jsc.letrec

### ISSUE THREAD

**Issue by stefanobaghino-da** [jsverify/jsverify#278]
I'm currently using `jsverify` in TypeScript to test a library that performs runtime structural type-checking on arbitrary objects. Some of these objects can have circular or recursive definitions, so to create the arbitrary instances for those (if I understood the documentation correctly) I have to use `letrec`. The problem is that (apparently) `letrec` is missing from the type definitions. If that is confirmed, I'd gladly provide a patch to fix this.

**Comment by stefanobaghino-da** [comment]
Solved by #279 :slightly_smiling_face:

**Comment by phadej** [comment]
Thanks!

**Comment by stefanobaghino** [comment]
My pleasure! Thanks for welcoming contributions and for helping this get done. Can't wait to bump the version in my project. :slightly_smiling_face:

**Comment by stefanobaghino-da** [comment]
Think it would be worth to cut a release? I'd like to start using this improvement. :slightly_smiling_face:

**Comment by stefanobaghino** [comment]
Think it would be worth to cut a release? I'd like to start using this improvement. :slightly_smiling_face:

**Comment by stefanobaghino** [comment]
Hey, I was wondering whether you're considering cutting a release, I'd like to use this in my code.
