### ISSUE TITLE
Suggestion for BDD style test helper

### ISSUE THREAD

**Issue by hexpunk** [jsverify/jsverify#281]
This isn't really an issue with jsverify as jsverify itself is properly agnostic of the actual test runner that's being used.

In my case, I'm using Jest.  To use jsverify and still keep my tests looking and feeling natural within the context of the rest of my unit tests, I made this little helper so that you can write a jsverify test almost the same way you'd write any other unit test in Jest.

```typescript
import * as jsc from 'jsverify';

/**
 * wrapper function for using jsverify with jest syntax
 *
 * @param description string describing the test
 * @param arbitrary a jsverify record (or other arbitrary)
 * @param testFn function that expects, in proper jest syntax
 * @param opts options for jsverify
 */
export function itHolds<A>(
  description: string,
  arbitrary: jsc.ArbitraryLike<A>,
  testFn: (val: A) => void,
  options: jsc.Options = {},
) {
  it(description, () => {
    jsc.assert(jsc.forall(arbitrary, (val: A) => {
      testFn(val);

      return true;
    }), options);
  });
}
```

Here's an example in use:
```typescript
import * as jsc from 'jsverify';

import { itHolds } from './itHolds';

describe('a simple jsverify test', () => {
  itHolds('(b && b) === b', jsc.bool, (b: boolean) => {
    expect(b && b).toBe(b);
  });

  // Obviously this next one fails, but stick with me.
  // I want to show you the resulting messages.
  itHolds('n > 100', jsc.nat, n => {
    expect(n).toBeGreaterThan(100);
  });
});
```

Here's the output from running that above test so you can see the fancy output:

```
 FAIL  __tests__/jsverifyExample.test.ts
  a simple jsverify test
    ✓ (b && b) === b (13ms)
    ✕ n > 100 (7ms)

  ● a simple jsverify test › n > 100

    Failed after 1 tests and 1 shrinks. rngState: 02f0d739b51284ea6c; Counterexample: 0; Exception: expect(received).toBeGreaterThan(expected)

    Expected: 100
    Received: 0

       9 |
      10 |   itHolds('n > 100', jsc.nat, n => {
    > 11 |     expect(n).toBeGreaterThan(100);
         |               ^
      12 |   });
      13 | });
      14 |

      at itHolds_1.itHolds.n (__tests__/jsverifyExample.test.ts:11:15)
      at jsc.assert.jsc.forall (__tests__/itHolds.ts:20:7)
      at Object.bind (../../node_modules/jsverify/lib/functor.js:48:11)
      at test (../../node_modules/jsverify/lib/jsverify.js:212:20)
      at ../../node_modules/jsverify/lib/jsverify.js:151:13
      at listFold (../../node_modules/lazy-seq/index.js:428:12)
      at Object.fold (../../node_modules/lazy-seq/index.js:438:12)
      at shrinkResult (../../node_modules/jsverify/lib/jsverify.js:150:25)
      at ../../node_modules/jsverify/lib/jsverify.js:233:16
      at Object.bind (../../node_modules/jsverify/lib/functor.js:63:12)
      at test (../../node_modules/jsverify/lib/jsverify.js:212:20)
      at ../../node_modules/jsverify/lib/jsverify.js:240:13
      at loop (../../node_modules/jsverify/lib/jsverify.js:316:26)
      at check (../../node_modules/jsverify/lib/jsverify.js:332:34)
      at Object.checkThrow [as assert] (../../node_modules/jsverify/lib/jsverify.js:354:34)
      at Object.it (__tests__/itHolds.ts:19:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        1.705s, estimated 2s
```

I hope this helps somebody make their tests and their tests' output nice and pretty.

**Comment by JayAndCatchFire** [comment]
You'll also note that I'm not using the DSL because I'm using Typescript, but it should be pretty easy to switch to using the DSL if desired.

**Comment by phadej** [comment]
Why `jsc.property` doesn't work. Can it be made to work with `jest` (not breaking `mocha` support though)?

**Comment by JayAndCatchFire** [comment]
`jsc.property` works fine in Jest. My `itHolds` function is just a convenience so you can use the `expect` assertions like any other unit test without having to `return true;` every time.

This issue wasn't meant to imply this code should be added to the library. It was more so if anyone else found themselves wanting something like this, they could borrow from my experience.

**Comment by adrianmcli** [comment]
Perhaps we could change the title of this issue to "Add official Jest support" and possibly consider adding the helper function to the repo? More and more people are using Jest and it would be great if this library supported it.

**Comment by phadej** [comment]
PR (with tests) are always welcome.

**Comment by adrianmcli** [comment]
@phadej great, I will start a new issue then.

**Comment by JayAndCatchFire** [comment]
I mentioned this in #290 but I thought I'd mention it here, too, since I see this has inspired #289.

This is all very cool. I'd just like to point out that none of this is exclusively applicable to Jest. It should apply to any BDD testing system that exposes an it function to the global scope, such as Chai (when configured to export it to the global scope such as some plug-ins for Karma do).

**Comment by adrianmcli** [comment]
@JayAndCatchFire There's an existing helper for Jasmine, and it exposes it to the global scope. But since this is a non-standard API, wouldn't it be good to require an explicit import of the helper? I'm open to generalizing it for any BDD testing system, but I don't really have much experience with Chai and Karma.

**Comment by JayAndCatchFire** [comment]
Unfortunately, it looks like the jasmine matcher can't be used wholesale.  Jest doesn't expose the same interface for adding matchers.  See here for how Jest does it: https://jestjs.io/docs/en/expect#expectextendmatchers

**Comment by hexpunk** [comment]
It's been 4 years.  I don't remember what my intention was with this issue.  I wasn't suggesting that this had to be included in jsverify.  I guess I was just sharing this with other jsverify users in case anyone else might benefit from it.  User-contributed documentation.  And the continued existence of this issue serves that purpose.
