### ISSUE TITLE
Question: how to best represent interdependent record members?

### ISSUE THREAD

**Issue by hexpunk** [jsverify/jsverify#298]
Is there an idiomatic way to create a record primitive/generator situation where one of the member's values is dependent on another member value.

For example, let's say I have a record that looks like this:
```javascript
jsc.record({ n: jsc.nat(100) })
```
I want to add another member `b` that is:
- a boolean
- `false` if `n` is less than 50
- `true` if `n` is greater than or equal to 50

Here's a more complex example.  Let's assume the same record as above.  But this time I want to add another member `s` that is:
- `jsc.nestring` if `n` is less than 50
- `jsc.constant(null)` if `n` is greater than or equal to 50

I know I can wrap the generation of these in a function or a custom generator, but as the number of these types of conditional members grows, it becomes unwieldy to write generators that way.  Is there a more idiomatic way to do this?  I was looking at `jsc.suchthat`, but I'm not sure if that's what I'm looking for.

**Comment by glebec** [comment]
@JayAndCatchFire 

Regarding your first example, that is a mapping of a generator where the `b` prop is entirely dependent on the `a` prop. The high-level tool for this is `smap`:

```
.smap(f: a -> b, g: b -> a, newShow: (b -> string)?): arbitrary b
```

```js
const recWithBool =
    jsc.record({ n: jsc.nat(100) })
    .smap(
        ({ n }) => ({ n, b: n < 50 }), // f: a -> b
        ({ n, b }) => ({ n }) // g: b -> a
    )
```

(Note that you don't actually have to explicitly destructure the `b` prop in the `g` function param above; I included it there to make it more obvious that we are "removing" the `b`.)

---

Your second example is significantly harder. You want an arbitrary value which _depends on the results of other arbitrary values_. Sequencing/chaining like this is what monad `flatmap` is for, but `jsverify` only provides `flatmap` for generators – not full arbitraries. That means you need to figure out the logic for your shrink manually.

```
.flatmap(f: a -> generator b): generator b
```

For the example you give of adding an `s` that is a either an `nestring` or a `constant(null)`, the generator part of the arbitrary would probably look something close to this (note I haven't tested this code, very possible there are errors especially w.r.t. JSVerify's namespacing / API method organization):

```js
const customArb = jsc.bless({
    generator: recWithBool.generator.flatmap(
        ({ n, b }) => {
            const newGen = n < 50 ? jsc.nestring.generator : jsc.generator.constant(null)
            return newGen.flatmap(
                (s) => jsc.generator.constant({ n, b, s })
            )
        },
    ),
    shrink: jsc.shrink.bless(({ n, b, s }) => {/* ... implementation ... */})
})
```

Writing the shrink is a bunch more work on top of that, though you could probably use some more `smap` to handle it.
