### ISSUE TITLE
notEmptyString arbitrary referred to in docs doesn't exist: was it updated to nestring?

### ISSUE THREAD

**Issue by stilenx** [jsverify/jsverify#66]
I can't find a notEmptyString property on jsverify, but searching the source turned up nestring. Unless I'm making an error, the docs should probably refer to nestring instead.

**Comment by phadej** [comment]
https://github.com/jsverify/jsverify/pull/61

**Comment by stilenx** [comment]
Thanks. And thank you for such an awesome project.
