### ISSUE TITLE
unit arbitrary

### ISSUE THREAD

**Issue by phadej** [jsverify/jsverify#70]
it's not so useful alone, but **is** useful as a building block.

**Comment by phadej** [comment]
Related to: https://github.com/jsverify/jsverify/issues/68

**Comment by phadej** [comment]
To be useful we need `sum`, (`product` ⇔ `tuple`)

**Comment by joneshf** [comment]
How do you want to represent this? `[]`, `{}`, `undefined`, `null`, an actual object, or something else?

**Comment by phadej** [comment]
I have some preliminary implementation in https://github.com/jsverify/jsverify/tree/unit branch.
I chose `[]`, because `unit` is *unit* element of product/tuple, which we represent as array.
