### ISSUE TITLE
Support for QUnit

### ISSUE THREAD

**Issue by zkessin** [jsverify/jsverify#90]
It would be nice if there was support for QUnit in jsverify

**Comment by phadej** [comment]
What kind of support you are looking for? I have no experience with QUnit.

Its npm download stats aren't very good:
- https://www.npmjs.com/package/qunit 15k last month
- https://www.npmjs.com/package/jasmine 237k last month
- https://www.npmjs.com/package/nodeunit 133k last month
- https://www.npmjs.com/package/mocha 1892k last month

So I wouldn't make this top priority issue. Dunno if people use it for in-browser testing though.

---

One could add a boilerplate reducing boilerplate from:

```js
QUnit.test("prop", function(assert) {
  var prop = jsc.foral(...);
  var r = jsc.check(prop);
  assert.ok(r === true, "Passed!"); // dunno how to report counterexample
});
```

to

```js
QUnit.property("=== reflexive", "nat", function (n) {
  return n === n;
});
```

Is this something you are looking for?

**Comment by omidfi** [comment]
I agree with phadej. Qunit has seen its good days while jQuery was hot.

**Comment by zkessin** [comment]
that kind of support would be pretty much it yes, but if the world has moved on to Mocha, then I am thinking I will focus there

**Comment by vredchenko** [comment]
Hi. I'd like to hook it up to Karma + Jasmine + Phantom. Has anyone bundled JSVerify for browser?

**Comment by phadej** [comment]
@vredchenko jsverify own test runs with `karma`, if it helps
