### ISSUE TITLE
undefined generator

### ISSUE THREAD

**Issue by fatuhoku** [jsverify/jsverify#93]
I've found that it's useful to test my function against `undefined` values only, as opposed to all kinds of falsy values produced by the `falsy` generator.

Any chance of implementing an undefined generator?

NB: I'm relatively new to Javascript so if I'm talking nonsense then let me know.

**Comment by StoneCypher** [comment]
There's only one `undefined`.  Just use `undefined` instead of a generator if that's what you want.

**Comment by joneshf** [comment]
Another option is to use `smap` on `unit`.

```javascript
var jsv = require('jsverify');
var always = require('ramda').always;

var undefinedArb = jsv.unit.smap(always(undefined), always([]), always("undefined")); 
```

Then you get your generator.

**Comment by phadej** [comment]
or
```js
var undefinedArb = jsc.constant(undefined);
var nullArb = jsc.constant(null);
// and so one for constants
```

**Comment by fatuhoku** [comment]
@phadej Ah. Of course. Thanks.
