### ISSUE TITLE
Generate unique sets / arrays

### ISSUE THREAD

**Issue by fatuhoku** [jsverify/jsverify#96]
Make a generator combinator that ensures the output does not have duplicates.

**Comment by phadej** [comment]
Equality comparison is difficult in JavaScript. Should we use `Object.is`, `===` or `_.isEqual`?
One could use `jsc.array(myGen).smap(_.uniq, _.identity)` or variants for now.

**Comment by phadej** [comment]
this functionality is now provided by https://github.com/jsverify/jsverify-contrib
