### ISSUE TITLE
Runtime error when generating int32 values

### ISSUE THREAD

**Issue by peterjoel** [jsverify/jsverify#98]
The int32 generator is currently unusable. It looks like the maxSize of int32 is too high (by 1), which causes an int check to fail.

Steps:
1. Use code like:

         jsc.int32.generator(100)

Expected Result:
Should generate an integer

Actual Result:
There is a runtime exception: "random takes one or two integer arguments"

Stack Trace:
RC4.random	@	rc4.js:97
randomInteger	@	random.js:20
(anonymous function)	@	primitive.js:55
(anonymous function)	@	VM5720:1
InjectedScript._evaluateOn	@	VM5277:883
InjectedScript._evaluateAndWrap	@	VM5277:816
InjectedScript.evaluateOnCallFrame	@	VM5277:942
RC4.random	@	rc4.js:86
randomInteger	@	random.js:20
(anonymous function)	@	primitive.js:55
(anonymous function)	@	VM5295:2
InjectedScript._evaluateOn	@	VM5277:883
InjectedScript._evaluateAndWrap	@	VM5277:816
InjectedScript.evaluate	@	VM5277:682

**Comment by phadej** [comment]
Weird. I'll fix this ASAP.
